tabWidth: 2
singleQuote: true
jsxSingleQuote: true
semi: true
trailingComma: all
printWidth: 120
endOfLine: lf
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - ^react((?!redux)(?!i18next).)*$
  - ^@?(?:react\-)?redux(.*)$
  - ^(?:react-)?i18next(.*)$
  - ^dayjs$
  - ^dayjs\/plugin\/(.+)$
  - <THIRD_PARTY_MODULES>
  - ^@test-helpers(.*)$
  - ^@webshop\/(.+)$
  - ^@styles(.*)$
  - ^\.\.?\/?(.(?!css))*$
  - ^dayjs\/locale\/(.+)$
  - ^\.\.?\/.+css$
importOrderSortSpecifiers: true
importOrderImportAttributesKeyword: with
